spring:
  application:
    name: MSALearningProject


  datasource:
    hikari:
      #jdbc-url: jdbc:h2:mem:msa;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1 # memory Mode
      jdbc-url: jdbc:h2:~/msa2;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1 # Embedded Mode
      driverClassName: org.h2.Driver
      username: msa
      password: msa
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    database-platform:  org.hibernate.dialect.H2Dialect

# Swagger URL Path
springdoc:
  swagger-ui:
    path: /msa/swagger.html

